[link1]
edges = ["H1", "S1"]
dataRate = "1Gbps"
delay = "2ms"
pcap = true

[link2]
edges = ["H2", "S2"]
dataRate = "1Gbps"
delay = "2ms"

[link3]
edges = ["S1", "S3"]
dataRate = "1Gbps"
delay = "5ms"

[link4]
edges = ["S1", "S4"]
dataRate = "1Gbps"
delay = "2ms"

[link5]
edges = ["S2", "S3"]
dataRate = "1Gbps"
delay = "2ms"

[link6]
edges = ["S2", "S4"]
dataRate = "1Gbps"
delay = "2ms"
