[link1]
edges = ["H1", "S1"]
dataRate = "1Gbps"
delay = "2ms"
pcap = true

[link2]
edges = ["H2", "S2"]
dataRate = "1Gbps"
delay = "2ms"

[link3]
edges = ["S2", "S1"]
dataRate = "1Gbps"
delay = "2ms"
