# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('switch-stats', ['core', "ofswitch13"])
    module.source = [
        'model/switch-stats.cc',
        'helper/switch-stats-helper.cc',
        'helper/switch-stats-logger.cc',
        ]

    module_test = bld.create_ns3_module_test_library('switch-stats')
    module_test.source = [
        'test/switch-stats-test-suite.cc',
        ]
    # Tests encapsulating example programs should be listed here
    if (bld.env['ENABLE_EXAMPLES']):
        module_test.source.extend([
        #    'test/switch-stats-examples-test-suite.cc',
             ])

    headers = bld(features='ns3header')
    headers.module = 'switch-stats'
    headers.source = [
        'model/switch-stats.h',
        'helper/switch-stats-helper.h',
        'helper/switch-stats-logger.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

