# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('snmp', ['core'])
    module.source = [
        'model/mib.cc',
        'model/mib-manager.cc',
        'model/energy-mib.cc',
        'helper/mib-helper.cc',
        'helper/mib-manager-helper.cc',
        'helper/mib-logger.cc',
        'helper/energy-mib-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('snmp')
    module_test.source = [
        'test/snmp-test-suite.cc',
        ]
    # Tests encapsulating example programs should be listed here
    if (bld.env['ENABLE_EXAMPLES']):
        module_test.source.extend([
        #    'test/snmp-examples-test-suite.cc',
             ])

    headers = bld(features='ns3header')
    headers.module = 'snmp'
    headers.source = [
        'model/mib.h',
        'model/mib-manager.h',
        'model/energy-mib.h',
        'helper/mib-helper.h',
        'helper/mib-manager-helper.h',
        'helper/mib-logger.h',
        'helper/energy-mib-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

